# Generated by Django 6.1.1 on 2026-09-06 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0002_caregiver_comfortable_with_pets_and_more'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', "En attente d'approbation"), ('APPROVED', 'Approuvée'), ('DENIED', 'Refusée')], default='PENDING', max_length=10)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='caregivers.caregiver')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='scheduling.visit')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('visit', 'caregiver'), name='uniq_visit_caregiver_request')],
            },
        ),
    ]
