# Generated by Django 6.1.1 on 2026-09-06 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0002_caregiver_comfortable_with_pets_and_more'),
        ('clients', '0002_client_caregiver_gender_preference_client_has_pets_and_more'),
        ('scheduling', '0002_visitrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdays', models.CharField(help_text='Comma-separated 0=Mon … 6=Sun', max_length=20)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=120)),
                ('start_date', models.DateField()),
                ('weeks', models.PositiveSmallIntegerField(default=4)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_schedules', to='caregivers.caregiver')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
