# Generated by Django 6.1.1 on 2026-09-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_recurringschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='hours_approved',
            field=models.BooleanField(default=False),
        ),
    ]
