# Generated by Django 6.1.1 on 2026-09-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='comfortable_with_pets',
            field=models.BooleanField(default=True, verbose_name="à l'aise avec les animaux"),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='comfortable_with_smoking',
            field=models.BooleanField(default=True, verbose_name="à l'aise en foyer fumeur"),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='gender',
            field=models.CharField(choices=[('U', 'Non précisé'), ('F', 'Femme'), ('M', 'Homme')], default='U', max_length=1),
        ),
    ]
