# Generated by Django 6.1.1 on 2026-09-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0002_caregiver_comfortable_with_pets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=7, verbose_name='taux horaire ($)'),
        ),
    ]
