# Generated by Django 6.1.1 on 2026-09-08 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0003_caregiver_pay_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='ex. T3 2026', max_length=40)),
                ('punctuality', models.PositiveSmallIntegerField(default=4)),
                ('care_quality', models.PositiveSmallIntegerField(default=4)),
                ('communication', models.PositiveSmallIntegerField(default=4)),
                ('professionalism', models.PositiveSmallIntegerField(default=4)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='caregivers.caregiver')),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
