# Generated by Django 6.1.1 on 2026-09-08 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0004_caregiverevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('doc_type', models.CharField(choices=[('ID', "Pièce d'identité"), ('CONTRACT', 'Contrat'), ('REFERENCE', 'Référence'), ('CERTIFICATE', 'Certificat'), ('MEDICAL', 'Visite médicale'), ('OTHER', 'Autre')], default='OTHER', max_length=12)),
                ('status', models.CharField(choices=[('VALID', 'Valide'), ('PENDING', 'En attente'), ('EXPIRED', 'Expiré')], default='VALID', max_length=8)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='caregivers.caregiver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
