# Generated by Django 6.1.1 on 2026-09-08 04:05

import uuid
import uuid
from django.db import migrations, models


def _tok(apps, schema_editor):
    C = apps.get_model("caregivers", "Caregiver")
    for cg in C.objects.all():
        cg.calendar_token = uuid.uuid4().hex
        cg.save(update_fields=["calendar_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0005_caregiverdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='calendar_token',
            field=models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=36),
        ),
            migrations.RunPython(_tok, migrations.RunPython.noop),
    ]
