# Generated by Django 6.1.1 on 2026-09-21 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0006_caregiver_calendar_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='assessment_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='applicant',
            name='experience',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='source',
            field=models.CharField(blank=True, help_text='Origine (recommandation, annonce…)', max_length=80),
        ),
        migrations.CreateModel(
            name='ApplicantEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='caregivers.applicant')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
