# Generated by Django 6.1.1 on 2026-09-20 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('purpose', models.TextField(blank=True)),
                ('proposed_at', models.DateTimeField()),
                ('duration_min', models.PositiveIntegerField(default=30)),
                ('location', models.CharField(blank=True, help_text='Salle ou lien visio', max_length=200)),
                ('status', models.CharField(choices=[('REQUESTED', 'Demandee'), ('CONFIRMED', 'Confirmee'), ('DECLINED', 'Refusee'), ('DONE', 'Terminee'), ('CANCELLED', 'Annulee')], default='REQUESTED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['proposed_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Accepte'), ('DECLINED', 'Refuse')], default='PENDING', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='collab.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('meeting', 'user')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='meetings', through='collab.MeetingParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('CERT', 'Certification'), ('UNCOVERED', 'Visite non couverte'), ('UNSIGNED', 'Rapport non signe'), ('HOURS', 'Heures a approuver'), ('INVOICE', 'Facture en retard'), ('FOLLOWUP', 'Relance client'), ('OTHER', 'Autre')], max_length=20)),
                ('priority', models.CharField(choices=[('HIGH', 'Haute'), ('MEDIUM', 'Moyenne'), ('LOW', 'Basse')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'A traiter'), ('SNOOZED', 'Reporte'), ('RESOLVED', 'Traite'), ('DISMISSED', 'Ignore')], db_index=True, default='OPEN', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkItemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='collab.workitem')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
