# Generated by Django 6.1.1 on 2026-09-21 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_dataaccesslog_consentrecord'),
        ('collab', '0002_meeting_room_token_meetingmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='clients.client'),
        ),
    ]
