# Generated by Django 6.1.1 on 2026-09-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='caregiver_gender_preference',
            field=models.CharField(choices=[('ANY', 'Indifférent'), ('FEMALE', 'Soignante (femme)'), ('MALE', 'Soignant (homme)')], default='ANY', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='has_pets',
            field=models.BooleanField(default=False, verbose_name="présence d'animaux"),
        ),
        migrations.AddField(
            model_name='client',
            name='smoking_household',
            field=models.BooleanField(default=False, verbose_name='foyer fumeur'),
        ),
    ]
