# Generated by Django 6.1.1 on 2026-09-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_invoice_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bill_rate',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=7, verbose_name='tarif horaire ($)'),
        ),
    ]
