# Generated by Django 6.1.1 on 2026-09-06 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_bill_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern_type', models.CharField(choices=[('WOUND', 'Plaie / escarre'), ('SKIN', 'Peau'), ('PAIN', 'Douleur'), ('MOBILITY', 'Mobilité'), ('NUTRITION', 'Nutrition'), ('COGNITIVE', 'Cognitif'), ('OTHER', 'Autre')], default='WOUND', max_length=12)),
                ('location', models.CharField(blank=True, help_text='ex. talon gauche', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('severity', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('OPEN', 'En cours'), ('IMPROVING', 'En amélioration'), ('RESOLVED', 'Résolue')], default='OPEN', max_length=10)),
                ('opened_on', models.DateField(blank=True, default=None, null=True)),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerns', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConcernUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('measurement', models.CharField(blank=True, help_text='ex. 3 cm × 2 cm', max_length=60)),
                ('status', models.CharField(choices=[('OPEN', 'En cours'), ('IMPROVING', 'En amélioration'), ('RESOLVED', 'Résolue')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='clients.careconcern')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
