# Generated by Django 6.1.1 on 2026-09-07 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_careconcern_concernupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('REFERRAL', 'Recommandation'), ('WEB', 'Site web'), ('PHONE', 'Téléphone'), ('HOSPITAL', 'Hôpital / clinique'), ('OTHER', 'Autre')], default='REFERRAL', max_length=12)),
                ('referred_by', models.CharField(blank=True, max_length=120)),
                ('care_need', models.CharField(blank=True, max_length=120)),
                ('stage', models.CharField(choices=[('NEW', 'Nouveau'), ('CONTACTED', 'Contacté'), ('ASSESSMENT', 'Évaluation'), ('CONVERTED', 'Converti'), ('LOST', 'Perdu')], default='NEW', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
