# Generated by Django 6.1.1 on 2026-09-08 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('hours_per_week', models.DecimalField(decimal_places=1, default=10, max_digits=6)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=8, max_digits=7)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('ENDED', 'Terminé')], default='ACTIVE', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
