# Generated by Django 6.1.1 on 2026-09-08 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clientcontract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessed_on', models.DateField()),
                ('mobility', models.CharField(choices=[('INDEPENDENT', 'Autonome'), ('ASSISTED', 'Aide partielle'), ('DEPENDENT', 'Dépendant')], default='ASSISTED', max_length=12)),
                ('cognition', models.CharField(choices=[('NORMAL', 'Normale'), ('MILD', 'Trouble léger'), ('MODERATE', 'Trouble modéré'), ('SEVERE', 'Trouble sévère')], default='NORMAL', max_length=10)),
                ('fall_risk', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], default='LOW', max_length=8)),
                ('adl_needs', models.CharField(blank=True, help_text='Comma-separated ADLs', max_length=300)),
                ('medical_notes', models.TextField(blank=True)),
                ('recommended_hours', models.DecimalField(decimal_places=1, default=10, max_digits=6)),
                ('recommended_care_type', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('COMPLETED', 'Terminée')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='clients.client')),
            ],
            options={
                'ordering': ['-assessed_on'],
            },
        ),
    ]
