# Generated by Django 6.1.1 on 2026-09-12 14:30

import secrets
from django.db import migrations, models


def _gen(apps, se):
    C = apps.get_model("clients", "Client")
    for c in C.objects.all():
        if not c.family_code:
            c.family_code = secrets.token_hex(3).upper()
            c.save(update_fields=["family_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_invoice_paid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='family_code',
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
        migrations.RunPython(_gen, migrations.RunPython.noop),
    ]
