# Generated by Django 6.1.1 on 2026-09-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_client_family_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, help_text='Description du service', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PAID', 'Payée'), ('PARTIAL', 'Partiellement payée'), ('DUE', 'À régler'), ('OVERDUE', 'En retard')], default='DUE', max_length=10),
        ),
    ]
