# Generated by Django 6.1.1 on 2026-09-20 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_invoice_amount_paid_invoice_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=120)),
                ('actor_role', models.CharField(blank=True, max_length=40)),
                ('what', models.CharField(default='Consultation du dossier', max_length=160)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='clients.client')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('CARE', 'Prestation des soins'), ('DATA', 'Traitement des données personnelles'), ('SHARE_FAMILY', 'Partage avec la famille'), ('MEDICAL', 'Accès aux informations médicales')], max_length=20)),
                ('text_version', models.CharField(default='v1', max_length=20)),
                ('granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('signed_by', models.CharField(blank=True, max_length=120)),
                ('signature', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='clients.client')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['purpose'],
                'unique_together': {('client', 'purpose')},
            },
        ),
    ]
