# Generated by Django 6.1.1 on 2026-09-22 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_dataaccesslog_consentrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CALL', 'Appel'), ('MESSAGE', 'Message'), ('EMAIL', 'E-mail'), ('MEETING', 'Réunion'), ('NOTE', 'Note'), ('STAGE', "Changement d'étape")], default='NOTE', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clients.lead')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
