# Generated by Django 6.1.1 on 2026-09-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_leadevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='next_action',
            field=models.CharField(blank=True, help_text='Prochaine action', max_length=200),
        ),
    ]
