# Generated by Django 6.1.1 on 2026-09-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_lead_next_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.CharField(choices=[('CARE', 'Soins / Coordinateur'), ('FINANCE', 'Finance / Facturation')], db_index=True, default='CARE', max_length=10),
        ),
    ]
