# Generated by Django 6.1.1 on 2026-09-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, db_index=True, help_text='Identifiant unique de connexion', max_length=40, verbose_name="numéro d'identification"),
        ),
    ]
