# Generated by Django 6.1.1 on 2026-09-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(default='Panther Home Care', max_length=120)),
                ('address', models.CharField(blank=True, default='Lubumbashi, RDC', max_length=200)),
                ('contact_email', models.EmailField(blank=True, default='contact@panthergroup.cd', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(default='$', max_length=6)),
                ('business_hours', models.CharField(default='08:00 – 18:00', max_length=60)),
                ('default_visit_minutes', models.PositiveIntegerField(default=120)),
                ('late_threshold_min', models.PositiveIntegerField(default=15, verbose_name='seuil de retard (min)')),
                ('geofence_km', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('require_gps', models.BooleanField(default=True)),
                ('max_weekly_hours', models.PositiveIntegerField(default=45)),
                ('max_travel_km', models.PositiveIntegerField(default=25)),
                ('auto_replacement', models.BooleanField(default=True, verbose_name='recherche auto de remplaçant')),
                ('default_bill_rate', models.DecimalField(decimal_places=2, default=8, max_digits=7)),
                ('default_pay_rate', models.DecimalField(decimal_places=2, default=5, max_digits=7)),
                ('payment_terms_days', models.PositiveIntegerField(default=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('automation_enabled', models.BooleanField(default=True)),
                ('ai_auto_fill', models.BooleanField(default=False, verbose_name="l'IA peut affecter automatiquement")),
                ('ai_confidence_threshold', models.PositiveIntegerField(default=80, verbose_name='seuil de confiance IA (%)')),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=False)),
                ('alert_late', models.BooleanField(default=True)),
                ('alert_missed', models.BooleanField(default=True)),
                ('alert_incident', models.BooleanField(default=True)),
                ('alert_cert', models.BooleanField(default=True)),
                ('alert_billing', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "paramètres de l'agence",
                'verbose_name_plural': "paramètres de l'agence",
            },
        ),
    ]
