# Generated by Django 6.1.1 on 2026-09-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_agencysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager (accès complet)'), ('ADMIN', 'Administrateur'), ('COORDINATOR', 'Coordinateur'), ('SUPERVISOR', 'Superviseur'), ('FINANCE', 'Financier'), ('CAREGIVER', 'Soignant'), ('FAMILY', 'Famille / Client'), ('CLINICAL', 'Conseiller clinique')], default='COORDINATOR', max_length=20),
        ),
    ]
