# Generated by Django 6.1.1 on 2026-09-05 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caregivers', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('mood', models.PositiveSmallIntegerField(choices=[(5, 'Très bien'), (4, 'Bien'), (3, 'Neutre'), (2, 'Bas'), (1, 'Mauvais')], default=3)),
                ('blood_pressure', models.CharField(blank=True, help_text='e.g. 120/80', max_length=20)),
                ('pulse', models.CharField(blank=True, help_text='bpm', max_length=20)),
                ('tasks_completed', models.JSONField(blank=True, default=list)),
                ('ai_flagged', models.BooleanField(default=False)),
                ('ai_concern', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caregivers.caregiver')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='scheduling.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
