# Generated by Django 6.1.1 on 2026-09-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carereport',
            name='insight_category',
            field=models.CharField(choices=[('MEDICAL', 'Médical'), ('CLINICAL', 'Clinique'), ('FUNCTIONAL', 'Fonctionnel'), ('GENERAL', 'Général')], default='GENERAL', max_length=12),
        ),
        migrations.AddField(
            model_name='carereport',
            name='insight_severity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
