# Generated by Django 6.1.1 on 2026-09-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_carereport_insight_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carereport',
            name='signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='carereport',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carereport',
            name='signed_by',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
