# Generated by Django 6.1.1 on 2026-09-21 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='incidents/%Y/%m/')),
                ('kind', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Vidéo'), ('FILE', 'Fichier')], default='PHOTO', max_length=6)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='incidents.incident')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=12)),
                ('note', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='incidents.incident')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
    ]
